icons_format = "{icon}"

# gruvbox colors
# bg			= #282828
# gray			= #928374
# bg0_h			= #1d2021
# purple 		= #b16286
# purple-light 		= #d3869b
# red 			= #cc241d
# red-light		= #fb4934
# orange		= #d65d0e
# orange-light		= #fe8019
[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "scratchpad"

[[block]]
block = "net"
format = " $icon D:$speed_down.eng(w:2) U:$speed_up.eng(w:2) "

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:30) $prev $play $next |}"
player = "spotify"
[block.theme_overrides]
info_bg = "#1d2021"

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/Istanbul?format=1' -s)"
interval = 600

[[block]]
block = "cpu"
critical_cpu = 90
format = " $icon $utilization "

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon  $utilization $memory $temperature $clocks "
idle = 60

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon  $mem_used.eng(w:4, prefix:Mi) / $mem_total.eng(w:4, prefix:Mi)($mem_used_percents.eng(w:2)) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = "us"
"Turkish (N/A)" = "tr"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[block.theme_overrides]
idle_bg = "#d3869b"
